### PR TITLE
[94] Add ability to filter out reported errors

### LINKED ISSUE #94: Investigate implementing FilterOut interface
https://coda.io/d/Tech-Working-Group_dq8QHMnEi6A/Aug-16th-2021-SteamcLog-Review_suivT#_luF5a

We want the ability to allow the applications to determine if a specific error should be blocked/filtered out from being logged to the remote destination. This is useful to help prevent noisy network errors from being incorrectly logged as non-fatal error reports.

### PR DESCRIPTION
**Pull request by jacobminer**
Closes #94 

Adds the ability to filter out errors using a lambda passed into the Config. By default, no errors are filtered out.

Screen Shot 2021-12-22 at 3 33 32 PM

### CODE REVIEW

**Review by JeremyChiang — APPROVED** [review]
Looks good to me!

My only non-blocking suggestion/thought is to rename `filterOut` to `sentryFilter`. Even with documentation, I was still confused for a few minutes thinking the filters would also mute logs.

File: SteamcLog/Classes/SteamcLog.swift [hunk 1]
```diff
@@ -262,6 +262,17 @@ public struct SteamcLog {
...
 
     public func error<T>(_ message: StaticString, _ object: T, functionName: StaticString = #function, fileName: StaticString = #file, lineNumber: Int = #line) where T: Encodable {
+
+        if let error = object as? Error, config.filterOut(error) {
+            info("\(error) on blocked list and has been blocked from being captured as an error: \(error.localizedDescription)",
+                 functionName: functionName,
+                 fileName: fileName,
+                 lineNumber: lineNumber
+            )
+            return
```
Comment (brendanlensink) [inline SteamcLog/Classes/SteamcLog.swift:272]: It could be handy to add a note at debug or verbose here mentioning which rule triggered the fitler

File: SteamcLog/Classes/Helper/Config.swift [hunk 2]
```diff
@@ -36,6 +36,9 @@ public struct Config {
     /// Toggles Sentry attaching stack traces  to errors. Default is true.
     internal let sentryAttachStacktrace: Bool
 
+    /// Toggles the ability to filter out errors from being reported to Sentry
+    internal let filterOut: FilterOut
```
Comment (brendanlensink) [inline SteamcLog/Classes/Helper/Config.swift:40]: Do you think it's worth changing this to `[FilterOut]` to allow users to filter out multiple different types of errors?

**Review by brendanlensink — CHANGES_REQUESTED** [review]
Two small suggestions. I also think that calling this feature `filterOut` is potentially confusing. I initially thought it completely filtered the message from being logged, rather than being a sentry/remote specific thing. 

Some possible alternatives:
skipRemote/Sentry
filterRemote/Sentry
ignoreRemote/Sentry

File: SteamcLog/Classes/SteamcLog.swift (hunk 1 above)
Comment (jacobminer) [reply SteamcLog/Classes/SteamcLog.swift:272]: Not sure what you mean by this? We've got the `info` call specifying that the error was filtered out via the SentryFilter (tweaked the wording above)

File: SteamcLog/Classes/Helper/Config.swift (hunk 2 above)
Comment (jacobminer) [reply SteamcLog/Classes/Helper/Config.swift:40]: Users can already filter out multiple types of errors via the interface, is there a benefit to allowing multiple objects? It seems like the Filter interface could use nested functions for organization

**Comment by jacobminer** [comment]
Changed the name from `FilterOut` to `SentryFilter` to be more clear!

File: SteamcLog/Classes/SteamcLog.swift (hunk 1 above)
Comment (brendanlensink) [reply SteamcLog/Classes/SteamcLog.swift:272]: I had assumed if we were able to set multiple filters, it would be helpful to log which filter caught the message

File: SteamcLog/Classes/Helper/Config.swift (hunk 2 above)
Comment (brendanlensink) [reply SteamcLog/Classes/Helper/Config.swift]: Oh of course, that works too 🚀

**Review by brendanlensink — APPROVED** [review]
